### PR TITLE
ToTW: Linting Documentation as Code

### PR DESCRIPTION
**Pull request by d33bs**
This PR adds content for a new "tip of the week" blog post covering a few tools which enable one to lint documentation similarly to code. I'd welcome any comments or suggestions you may have, thanks a bunch!

### CODE REVIEW

**Comment by vincerubinetti** [comment]
Looks like the `two-col` code block problem is due to a `min-width` being set somewhere on one of the children elements, preventing the cols from shrinking as they should. I also noticed some other css bugs with it (padding), so let me fix it up before merging.

**Comment by d33bs** [comment]
Sounds good, thank you @vincerubinetti !

**Comment by vincerubinetti** [comment]
You can apply this commit and it should fix it:
https://github.com/greenelab/lab-website-template/commit/ad4a6eb241b72bdffc649ccb94d0686dc491a233

**Review by vincerubinetti — APPROVED** [review]
Very useful article!

**Comment by d33bs** [comment]
Thanks again @vincerubinetti !

**Review by falquaddoomi — APPROVED** [review]
The content looks great, and with the CSS fixes the presentation does, too. Nice work!

**Comment by d33bs** [comment]
Thank you @falquaddoomi !

**Pull request merged**
